[bridges]

[bridges.bridge-1]
op_node_public_rpc_url = 'http://127.0.0.1:8545'
op_node_p2p_rpc_url = 'http://127.0.0.1:8545'
op_geth_public_rpc_url = 'http://127.0.0.1:8545'

[bridges.bridge-2]
op_node_public_rpc_url = 'http://127.0.0.1:8545'
op_node_p2p_rpc_url = 'http://127.0.0.1:8545'
op_geth_public_rpc_url = 'http://127.0.0.1:8545'

[sequencers]

[sequencers.sequencers-1]
op_node_public_rpc_url = 'http://127.0.0.1:8545'
op_node_p2p_rpc_url = 'http://127.0.0.1:8545'
op_geth_public_rpc_url = 'http://127.0.0.1:8545'

[sequencers.sequencers-2]
op_node_public_rpc_url = 'http://127.0.0.1:8545'
op_node_p2p_rpc_url = 'http://127.0.0.1:8545'
op_geth_public_rpc_url = 'http://127.0.0.1:8545'

[sequencers.sequencers-3]
op_node_public_rpc_url = 'http://127.0.0.1:8545'
op_node_p2p_rpc_url = 'http://127.0.0.1:8545'
op_geth_public_rpc_url = 'http://127.0.0.1:8545'

[metrics]
host = "0.0.0.0"
port = 9761
[rpc]
host = "0.0.0.0"
port = 9762
